# Generated by Django 5.2.6 on 2026-10-02 01:33

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.utils.timezone
import tutorias.models
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutorias', '0001_extensiones'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueDisponibilidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inicio_en', models.DateTimeField()),
                ('fin_en', models.DateTimeField()),
                ('estado', models.CharField(choices=[('LIBRE', 'Libre'), ('OCUPADO', 'Ocupado'), ('ELIMINADO', 'Eliminado')], default='LIBRE', max_length=10)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bloque_disponibilidad',
            },
        ),
        migrations.CreateModel(
            name='AsignaturaRef',
            fields=[
                ('asignatura_id', models.UUIDField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=150)),
                ('actualizado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'asignatura_ref',
                'indexes': [models.Index(fields=['sigla'], name='ix_asignatura_ref_sigla')],
            },
        ),
        migrations.CreateModel(
            name='EjecucionTarea',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comando', models.CharField(max_length=40)),
                ('solicitudes_expiradas', models.IntegerField(default=0)),
                ('reservas_cerradas', models.IntegerField(default=0)),
                ('refs_sincronizadas', models.IntegerField(default=0)),
                ('perfiles_desactivados', models.IntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=300, null=True)),
                ('iniciada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('terminada_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ejecucion_tarea',
                'indexes': [models.Index(fields=['-iniciada_en'], name='ix_ejecucion_fecha')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioRef',
            fields=[
                ('usuario_id', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('carrera_id', models.UUIDField(blank=True, null=True)),
                ('sede_id', models.UUIDField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('reputacion_promedio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('reputacion_total', models.IntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'usuario_ref',
                'indexes': [models.Index(fields=['actualizado_en'], name='ix_usuario_ref_refresco')],
                'constraints': [models.CheckConstraint(condition=models.Q(('reputacion_promedio__gte', 0), ('reputacion_promedio__lte', 5)), name='ck_usuario_ref_promedio'), models.CheckConstraint(condition=models.Q(('reputacion_total__gte', 0)), name='ck_usuario_ref_total')],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('CONFIRMADA', 'Confirmada'), ('RECHAZADA', 'Rechazada'), ('EXPIRADA', 'Expirada'), ('CANCELADA', 'Cancelada'), ('REALIZADA', 'Realizada'), ('EVALUADA', 'Evaluada')], default='SOLICITADA', max_length=12)),
                ('nota', models.CharField(blank=True, max_length=500, null=True)),
                ('modalidad', models.CharField(blank=True, choices=[('PRESENCIAL', 'Presencial'), ('EN_LINEA', 'En línea')], max_length=12, null=True)),
                ('lugar_o_enlace', models.CharField(blank=True, max_length=300, null=True)),
                ('monto', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=8)),
                ('estado_pago', models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('FALLIDO', 'Fallido'), ('REEMBOLSADO', 'Reembolsado')], max_length=12, null=True)),
                ('pago_actualizado_en', models.DateTimeField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmada_en', models.DateTimeField(blank=True, null=True)),
                ('cerrada_en', models.DateTimeField(blank=True, null=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservas', to='tutorias.asignaturaref')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservas', to='tutorias.bloquedisponibilidad')),
                ('cancelada_por_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='reservas_canceladas', to='tutorias.usuarioref')),
                ('solicitante_usuario', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='reservas_solicitadas', to='tutorias.usuarioref')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='PerfilTutor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tarifa', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=8)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.RESTRICT, related_name='perfiles', to='tutorias.asignaturaref')),
                ('usuario', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to='tutorias.usuarioref')),
            ],
            options={
                'db_table': 'perfil_tutor',
            },
        ),
        migrations.AddField(
            model_name='bloquedisponibilidad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='tutorias.usuarioref'),
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calificacion', models.SmallIntegerField()),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('retirada_en', models.DateTimeField(blank=True, null=True)),
                ('retirada_por_usuario_id', models.UUIDField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='tutorias.reserva')),
            ],
            options={
                'db_table': 'evaluacion',
                'indexes': [models.Index(condition=models.Q(('retirada_en__isnull', True)), fields=['reserva'], name='ix_evaluacion_visible')],
                'constraints': [models.CheckConstraint(condition=models.Q(('calificacion__gte', 1), ('calificacion__lte', 5)), name='ck_evaluacion_calificacion'), models.CheckConstraint(condition=models.Q(models.Q(('retirada_en__isnull', True), ('retirada_por_usuario_id__isnull', True)), models.Q(('retirada_en__isnull', False), ('retirada_por_usuario_id__isnull', False)), _connector='OR'), name='ck_evaluacion_retiro')],
            },
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['solicitante_usuario', '-creada_en'], name='ix_reserva_solicitante'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(condition=models.Q(('estado', 'SOLICITADA')), fields=['bloque'], name='ix_reserva_pendientes'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['SOLICITADA', 'CONFIRMADA', 'RECHAZADA', 'EXPIRADA', 'CANCELADA', 'REALIZADA', 'EVALUADA'])), name='ck_reserva_estado'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('modalidad__isnull', True), ('modalidad__in', ['PRESENCIAL', 'EN_LINEA']), _connector='OR'), name='ck_reserva_modalidad'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('estado_pago__isnull', True), ('estado_pago__in', ['PENDIENTE', 'PAGADO', 'FALLIDO', 'REEMBOLSADO']), _connector='OR'), name='ck_reserva_estado_pago'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gte', 0)), name='ck_reserva_monto'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado__in', ['CONFIRMADA', 'REALIZADA', 'EVALUADA']), _negated=True), models.Q(('confirmada_en__isnull', False), ('lugar_o_enlace__isnull', False), ('modalidad__isnull', False)), _connector='OR'), name='ck_reserva_confirmada_completa'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(condition=models.Q(('estado_pago__isnull', True), ('monto__gt', 0), _connector='OR'), name='ck_reserva_pago_con_monto'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['CONFIRMADA', 'REALIZADA', 'EVALUADA'])), fields=('bloque',), name='ux_reserva_bloque_ocupado'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'SOLICITADA')), fields=('bloque', 'solicitante_usuario'), name='ux_reserva_solicitud_unica'),
        ),
        migrations.AddIndex(
            model_name='perfiltutor',
            index=models.Index(fields=['asignatura', 'activo'], include=('usuario', 'tarifa'), name='ix_perfil_busqueda'),
        ),
        migrations.AddIndex(
            model_name='perfiltutor',
            index=models.Index(fields=['usuario'], name='ix_perfil_usuario'),
        ),
        migrations.AddConstraint(
            model_name='perfiltutor',
            constraint=models.UniqueConstraint(fields=('usuario', 'asignatura'), name='ux_perfil_usuario_asignatura'),
        ),
        migrations.AddConstraint(
            model_name='perfiltutor',
            constraint=models.CheckConstraint(condition=models.Q(('tarifa__gte', 0)), name='ck_perfil_tarifa'),
        ),
        migrations.AddIndex(
            model_name='bloquedisponibilidad',
            index=models.Index(condition=models.Q(('estado', 'LIBRE')), fields=['usuario', 'inicio_en'], name='ix_bloque_libre'),
        ),
        migrations.AddIndex(
            model_name='bloquedisponibilidad',
            index=models.Index(fields=['inicio_en'], name='ix_bloque_inicio'),
        ),
        migrations.AddConstraint(
            model_name='bloquedisponibilidad',
            constraint=models.CheckConstraint(condition=models.Q(('fin_en__gt', models.F('inicio_en'))), name='ck_bloque_fin_posterior'),
        ),
        migrations.AddConstraint(
            model_name='bloquedisponibilidad',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['LIBRE', 'OCUPADO', 'ELIMINADO'])), name='ck_bloque_estado'),
        ),
        migrations.AddConstraint(
            model_name='bloquedisponibilidad',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('estado', 'ELIMINADO'), _negated=True), expressions=[('usuario', '='), (tutorias.models.TsTzRange('inicio_en', 'fin_en', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='ex_bloque_sin_solape'),
        ),
    ]
