# Generated by Django 5.2.6 on 2026-10-02 01:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reserva_id', models.UUIDField()),
                ('monto', models.DecimalField(decimal_places=0, max_digits=8)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('FALLIDO', 'Fallido'), ('REEMBOLSADO', 'Reembolsado')], default='PENDIENTE', max_length=12)),
                ('proveedor', models.CharField(default='SIMULADO', max_length=30)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('notificado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pago',
                'indexes': [models.Index(condition=models.Q(('notificado_en__isnull', True), models.Q(('estado', 'PENDIENTE'), _negated=True)), fields=['id'], name='ix_pago_sin_notificar')],
                'constraints': [models.UniqueConstraint(fields=('reserva_id',), name='ux_pago_reserva'), models.UniqueConstraint(condition=models.Q(('referencia_externa__isnull', False)), fields=('proveedor', 'referencia_externa'), name='ux_pago_referencia'), models.CheckConstraint(condition=models.Q(('estado__in', ['PENDIENTE', 'PAGADO', 'FALLIDO', 'REEMBOLSADO'])), name='ck_pago_estado'), models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='ck_pago_monto')],
            },
        ),
        migrations.CreateModel(
            name='IntentoPago',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('COBRO', 'Cobro'), ('REEMBOLSO', 'Reembolso')], default='COBRO', max_length=10)),
                ('resultado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido')], max_length=10)),
                ('mensaje', models.CharField(blank=True, max_length=200, null=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('pago', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='pagos.pago')),
            ],
            options={
                'db_table': 'intento_pago',
                'indexes': [models.Index(fields=['pago', '-creado_en'], name='ix_intento_pago')],
                'constraints': [models.CheckConstraint(condition=models.Q(('tipo__in', ['COBRO', 'REEMBOLSO'])), name='ck_intento_tipo'), models.CheckConstraint(condition=models.Q(('resultado__in', ['EXITOSO', 'FALLIDO'])), name='ck_intento_resultado')],
            },
        ),
    ]
