name: plataforma-tutorias

services:

  identity:
    build: ./services/identity
    container_name: tut_identity
    restart: unless-stopped
    environment:
      NOMBRE_SERVICIO: identity
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      POSTGRES_HOST: identity_db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${IDENTITY_DB_NAME}
      POSTGRES_USER: ${IDENTITY_DB_USER}
      POSTGRES_PASSWORD: ${IDENTITY_DB_PASSWORD}
    depends_on:
      identity_db:
        condition: service_healthy

  identity_db:
    image: postgres:16
    container_name: tut_identity_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${IDENTITY_DB_NAME}
      POSTGRES_USER: ${IDENTITY_DB_USER}
      POSTGRES_PASSWORD: ${IDENTITY_DB_PASSWORD}
    volumes:
      - datos_identity:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 12

volumes:
  datos_identity:
