# Generated by Django 5.2.6 on 2026-10-02 00:40

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=150)),
                ('password', models.CharField(db_column='password_hash', max_length=128)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('carrera_id', models.UUIDField(blank=True, null=True)),
                ('nivel', models.SmallIntegerField(blank=True, null=True)),
                ('sede_id', models.UUIDField(blank=True, null=True)),
                ('email_verificado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('es_admin', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usuario',
                'indexes': [models.Index(fields=['activo', '-creado_en'], name='ix_usuario_admin')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='ux_usuario_email'), models.CheckConstraint(condition=models.Q(('email__iendswith', '@duocuc.cl')), name='ck_usuario_email_dominio'), models.CheckConstraint(condition=models.Q(('nivel__isnull', True), models.Q(('nivel__gte', 1), ('nivel__lte', 12)), _connector='OR'), name='ck_usuario_nivel')],
            },
        ),
        migrations.CreateModel(
            name='AvisoCorreo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('plantilla', models.CharField(choices=[('VERIFICACION_CORREO', 'Verificación del correo'), ('SOLICITUD_RECIBIDA', 'Solicitud recibida'), ('RESERVA_CONFIRMADA', 'Reserva confirmada'), ('RESERVA_RECHAZADA', 'Reserva rechazada'), ('RESERVA_CANCELADA', 'Reserva cancelada'), ('CUENTA_DESACTIVADA', 'Cuenta desactivada')], max_length=40)),
                ('asunto', models.CharField(max_length=150)),
                ('referencia_id', models.UUIDField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido')], default='ENVIADO', max_length=10)),
                ('error', models.CharField(blank=True, max_length=300, null=True)),
                ('enviado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='cuentas.usuario')),
            ],
            options={
                'db_table': 'aviso_correo',
                'indexes': [models.Index(fields=['usuario', '-enviado_en'], name='ix_aviso_usuario')],
                'constraints': [models.CheckConstraint(condition=models.Q(('plantilla__in', ['VERIFICACION_CORREO', 'SOLICITUD_RECIBIDA', 'RESERVA_CONFIRMADA', 'RESERVA_RECHAZADA', 'RESERVA_CANCELADA', 'CUENTA_DESACTIVADA'])), name='ck_aviso_plantilla'), models.CheckConstraint(condition=models.Q(('estado__in', ['ENVIADO', 'FALLIDO'])), name='ck_aviso_estado'), models.UniqueConstraint(condition=models.Q(('referencia_id__isnull', False)), fields=('plantilla', 'referencia_id', 'usuario'), name='ux_aviso_idempotente')],
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64)),
                ('expira_en', models.DateTimeField()),
                ('revocado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='cuentas.usuario')),
            ],
            options={
                'db_table': 'refresh_token',
                'indexes': [models.Index(condition=models.Q(('revocado_en__isnull', True)), fields=['usuario'], name='ix_refresh_activo')],
                'constraints': [models.UniqueConstraint(fields=('token_hash',), name='ux_refresh_hash'), models.CheckConstraint(condition=models.Q(('expira_en__gt', models.F('creado_en'))), name='ck_refresh_expira')],
            },
        ),
        migrations.CreateModel(
            name='TokenVerificacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64)),
                ('expira_en', models.DateTimeField()),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_verificacion', to='cuentas.usuario')),
            ],
            options={
                'db_table': 'token_verificacion',
                'indexes': [models.Index(condition=models.Q(('usado_en__isnull', True)), fields=['usuario'], name='ix_token_verif_vigente')],
                'constraints': [models.UniqueConstraint(fields=('token_hash',), name='ux_token_verif_hash'), models.CheckConstraint(condition=models.Q(('expira_en__gt', models.F('creado_en'))), name='ck_token_verif_expira')],
            },
        ),
    ]
