# Generated by Django 5.2.6 on 2026-10-02 01:19

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_extensiones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=150)),
                ('creditos', models.SmallIntegerField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'asignatura',
                'indexes': [django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('sigla'), name='gin_trgm_ops'), django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('nombre'), name='gin_trgm_ops'), name='ix_asignatura_busqueda')],
                'constraints': [models.UniqueConstraint(fields=('sigla',), name='ux_asignatura_sigla'), models.CheckConstraint(condition=models.Q(('creditos__isnull', True), models.Q(('creditos__gte', 1), ('creditos__lte', 30)), _connector='OR'), name='ck_asignatura_creditos')],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('escuela', models.CharField(max_length=120)),
                ('activa', models.BooleanField(default=True)),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'carrera',
                'indexes': [models.Index(fields=['activa', 'nombre'], name='ix_carrera_activa')],
                'constraints': [models.UniqueConstraint(fields=('codigo',), name='ux_carrera_codigo')],
            },
        ),
        migrations.CreateModel(
            name='ImportacionCatalogo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('archivo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('CARRERAS', 'Carreras'), ('ASIGNATURAS', 'Asignaturas'), ('MALLA', 'Malla'), ('SEDES', 'Sedes')], max_length=20)),
                ('filas_leidas', models.IntegerField(default=0)),
                ('filas_creadas', models.IntegerField(default=0)),
                ('filas_omitidas', models.IntegerField(default=0)),
                ('ejecutada_por', models.UUIDField(blank=True, null=True)),
                ('ejecutada_en', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'importacion_catalogo',
                'indexes': [models.Index(fields=['-ejecutada_en'], name='ix_importacion_fecha')],
                'constraints': [models.CheckConstraint(condition=models.Q(('tipo__in', ['CARRERAS', 'ASIGNATURAS', 'MALLA', 'SEDES'])), name='ck_importacion_tipo')],
            },
        ),
        migrations.CreateModel(
            name='Malla',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('carrera', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='mallas', to='catalogo.carrera')),
            ],
            options={
                'db_table': 'malla',
            },
        ),
        migrations.CreateModel(
            name='MallaAsignatura',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('semestre', models.SmallIntegerField()),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='en_mallas', to='catalogo.asignatura')),
                ('malla', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='catalogo.malla')),
            ],
            options={
                'db_table': 'malla_asignatura',
            },
        ),
        migrations.CreateModel(
            name='Prerrequisito',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('malla_asignatura', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='prerrequisitos', to='catalogo.mallaasignatura')),
                ('requiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exigida_por', to='catalogo.mallaasignatura')),
            ],
            options={
                'db_table': 'prerrequisito',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('region', models.CharField(blank=True, max_length=80, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sede',
                'indexes': [models.Index(fields=['activa', 'nombre'], name='ix_sede_activa')],
                'constraints': [models.UniqueConstraint(fields=('codigo',), name='ux_sede_codigo')],
            },
        ),
        migrations.CreateModel(
            name='ImportacionError',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fila', models.IntegerField()),
                ('mensaje', models.CharField(max_length=300)),
                ('importacion', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='errores', to='catalogo.importacioncatalogo')),
            ],
            options={
                'db_table': 'importacion_error',
                'indexes': [models.Index(fields=['importacion', 'fila'], name='ix_importacion_error')],
                'constraints': [models.CheckConstraint(condition=models.Q(('fila__gte', 1)), name='ck_importacion_error_fila')],
            },
        ),
        migrations.AddIndex(
            model_name='malla',
            index=models.Index(fields=['carrera'], name='ix_malla_carrera'),
        ),
        migrations.AddConstraint(
            model_name='malla',
            constraint=models.UniqueConstraint(fields=('carrera', 'version'), name='ux_malla_carrera_version'),
        ),
        migrations.AddConstraint(
            model_name='malla',
            constraint=models.CheckConstraint(condition=models.Q(('vigente_hasta__isnull', True), ('vigente_hasta__gt', models.F('vigente_desde')), _connector='OR'), name='ck_malla_vigencia'),
        ),
        migrations.AddConstraint(
            model_name='malla',
            constraint=models.UniqueConstraint(condition=models.Q(('vigente_hasta__isnull', True)), fields=('carrera',), name='ux_malla_vigente'),
        ),
        migrations.AddIndex(
            model_name='mallaasignatura',
            index=models.Index(fields=['malla', 'semestre'], include=('asignatura',), name='ix_malla_asig_semestre'),
        ),
        migrations.AddConstraint(
            model_name='mallaasignatura',
            constraint=models.UniqueConstraint(fields=('malla', 'asignatura'), name='ux_malla_asignatura'),
        ),
        migrations.AddConstraint(
            model_name='mallaasignatura',
            constraint=models.CheckConstraint(condition=models.Q(('semestre__gte', 1), ('semestre__lte', 12)), name='ck_malla_asig_semestre'),
        ),
        migrations.AddIndex(
            model_name='prerrequisito',
            index=models.Index(fields=['malla_asignatura'], name='ix_prerrequisito_origen'),
        ),
        migrations.AddConstraint(
            model_name='prerrequisito',
            constraint=models.UniqueConstraint(fields=('malla_asignatura', 'requiere'), name='ux_prerrequisito'),
        ),
        migrations.AddConstraint(
            model_name='prerrequisito',
            constraint=models.CheckConstraint(condition=models.Q(('malla_asignatura_id', models.F('requiere_id')), _negated=True), name='ck_prerrequisito_distinto'),
        ),
    ]
