--
-- PostgreSQL database dump
--

\restrict 5A5FC9jSeUYnA8KfyhlWRd2v46jTHhnv2qHYLrTHqh5nwwiMYu7w9rn2mOpUO7U

-- Dumped from database version 16.15 (Debian 16.15-1.pgdg13+2)
-- Dumped by pg_dump version 16.15 (Debian 16.15-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: asignatura; Type: TABLE; Schema: public; Owner: catalog
--

CREATE TABLE public.asignatura (
    id uuid NOT NULL,
    sigla character varying(15) NOT NULL,
    nombre character varying(150) NOT NULL,
    creditos smallint,
    activa boolean NOT NULL,
    creada_en timestamp with time zone NOT NULL,
    CONSTRAINT ck_asignatura_creditos CHECK (((creditos IS NULL) OR ((creditos >= 1) AND (creditos <= 30))))
);


ALTER TABLE public.asignatura OWNER TO catalog;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: catalog
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO catalog;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: catalog
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: catalog
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO catalog;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: catalog
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: catalog
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO catalog;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: catalog
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: catalog
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO catalog;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: catalog
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO catalog;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: catalog
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: catalog
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: catalog
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO catalog;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: catalog
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: carrera; Type: TABLE; Schema: public; Owner: catalog
--

CREATE TABLE public.carrera (
    id uuid NOT NULL,
    codigo character varying(20) NOT NULL,
    nombre character varying(150) NOT NULL,
    escuela character varying(120) NOT NULL,
    activa boolean NOT NULL,
    creada_en timestamp with time zone NOT NULL
);


ALTER TABLE public.carrera OWNER TO catalog;

--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: catalog
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO catalog;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: catalog
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: catalog
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO catalog;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: catalog
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: importacion_catalogo; Type: TABLE; Schema: public; Owner: catalog
--

CREATE TABLE public.importacion_catalogo (
    id bigint NOT NULL,
    archivo character varying(200) NOT NULL,
    tipo character varying(20) NOT NULL,
    filas_leidas integer NOT NULL,
    filas_creadas integer NOT NULL,
    filas_omitidas integer NOT NULL,
    ejecutada_por uuid,
    ejecutada_en timestamp with time zone NOT NULL,
    CONSTRAINT ck_importacion_tipo CHECK (((tipo)::text = ANY ((ARRAY['CARRERAS'::character varying, 'ASIGNATURAS'::character varying, 'MALLA'::character varying, 'SEDES'::character varying])::text[])))
);


ALTER TABLE public.importacion_catalogo OWNER TO catalog;

--
-- Name: importacion_catalogo_id_seq; Type: SEQUENCE; Schema: public; Owner: catalog
--

ALTER TABLE public.importacion_catalogo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.importacion_catalogo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: importacion_error; Type: TABLE; Schema: public; Owner: catalog
--

CREATE TABLE public.importacion_error (
    id bigint NOT NULL,
    fila integer NOT NULL,
    mensaje character varying(300) NOT NULL,
    importacion_id bigint NOT NULL,
    CONSTRAINT ck_importacion_error_fila CHECK ((fila >= 1))
);


ALTER TABLE public.importacion_error OWNER TO catalog;

--
-- Name: importacion_error_id_seq; Type: SEQUENCE; Schema: public; Owner: catalog
--

ALTER TABLE public.importacion_error ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.importacion_error_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: malla; Type: TABLE; Schema: public; Owner: catalog
--

CREATE TABLE public.malla (
    id bigint NOT NULL,
    version character varying(20) NOT NULL,
    vigente_desde date NOT NULL,
    vigente_hasta date,
    creada_en timestamp with time zone NOT NULL,
    carrera_id uuid NOT NULL,
    CONSTRAINT ck_malla_vigencia CHECK (((vigente_hasta IS NULL) OR (vigente_hasta > vigente_desde)))
);


ALTER TABLE public.malla OWNER TO catalog;

--
-- Name: malla_asignatura; Type: TABLE; Schema: public; Owner: catalog
--

CREATE TABLE public.malla_asignatura (
    id bigint NOT NULL,
    semestre smallint NOT NULL,
    asignatura_id uuid NOT NULL,
    malla_id bigint NOT NULL,
    CONSTRAINT ck_malla_asig_semestre CHECK (((semestre >= 1) AND (semestre <= 12)))
);


ALTER TABLE public.malla_asignatura OWNER TO catalog;

--
-- Name: malla_asignatura_id_seq; Type: SEQUENCE; Schema: public; Owner: catalog
--

ALTER TABLE public.malla_asignatura ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.malla_asignatura_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: malla_id_seq; Type: SEQUENCE; Schema: public; Owner: catalog
--

ALTER TABLE public.malla ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.malla_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prerrequisito; Type: TABLE; Schema: public; Owner: catalog
--

CREATE TABLE public.prerrequisito (
    id bigint NOT NULL,
    malla_asignatura_id bigint NOT NULL,
    requiere_id bigint NOT NULL,
    CONSTRAINT ck_prerrequisito_distinto CHECK ((NOT (malla_asignatura_id = requiere_id)))
);


ALTER TABLE public.prerrequisito OWNER TO catalog;

--
-- Name: prerrequisito_id_seq; Type: SEQUENCE; Schema: public; Owner: catalog
--

ALTER TABLE public.prerrequisito ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prerrequisito_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sede; Type: TABLE; Schema: public; Owner: catalog
--

CREATE TABLE public.sede (
    id uuid NOT NULL,
    codigo character varying(20) NOT NULL,
    nombre character varying(120) NOT NULL,
    region character varying(80),
    activa boolean NOT NULL
);


ALTER TABLE public.sede OWNER TO catalog;

--
-- Data for Name: asignatura; Type: TABLE DATA; Schema: public; Owner: catalog
--

COPY public.asignatura (id, sigla, nombre, creditos, activa, creada_en) FROM stdin;
40000000-0000-4000-8000-000000000001	MAT1101	Matemática Aplicada	6	t	2026-09-20 15:00:00+00
40000000-0000-4000-8000-000000000002	ING1101	Inglés Elemental	4	t	2026-09-20 15:00:00+00
40000000-0000-4000-8000-000000000003	ETI1101	Ética para el Trabajo	3	t	2026-09-20 15:00:00+00
40000000-0000-4000-8000-000000000004	EST2101	Estadística Descriptiva	5	t	2026-09-20 15:00:00+00
40000000-0000-4000-8000-000000000005	PRO1101	Programación de Algoritmos	8	t	2026-09-20 15:00:00+00
40000000-0000-4000-8000-000000000006	BDD1101	Base de Datos	6	t	2026-09-20 15:00:00+00
40000000-0000-4000-8000-000000000007	PRO2101	Programación Orientada a Objetos	8	t	2026-09-20 15:00:00+00
40000000-0000-4000-8000-000000000008	WEB2101	Desarrollo Web	6	t	2026-09-20 15:00:00+00
40000000-0000-4000-8000-000000000009	BDD2101	Programación de Base de Datos	6	t	2026-09-20 15:00:00+00
40000000-0000-4000-8000-000000000010	RED1101	Fundamentos de Redes	5	t	2026-09-20 15:00:00+00
40000000-0000-4000-8000-000000000011	SIS3101	Arquitectura de Software	6	t	2026-09-20 15:00:00+00
40000000-0000-4000-8000-000000000012	MOV3101	Desarrollo de Aplicaciones Móviles	6	t	2026-09-20 15:00:00+00
40000000-0000-4000-8000-000000000013	SEG3101	Seguridad en Sistemas	5	t	2026-09-20 15:00:00+00
40000000-0000-4000-8000-000000000014	ING2101	Inglés Intermedio	4	t	2026-09-20 15:00:00+00
40000000-0000-4000-8000-000000000015	ADM1101	Fundamentos de Administración	6	t	2026-09-20 15:00:00+00
40000000-0000-4000-8000-000000000016	CON1101	Contabilidad Básica	6	t	2026-09-20 15:00:00+00
40000000-0000-4000-8000-000000000017	ECO2101	Microeconomía	5	t	2026-09-20 15:00:00+00
40000000-0000-4000-8000-000000000018	FIN2101	Matemática Financiera	5	t	2026-09-20 15:00:00+00
40000000-0000-4000-8000-000000000019	MKT3101	Marketing	5	t	2026-09-20 15:00:00+00
40000000-0000-4000-8000-000000000020	RRH3101	Gestión de Personas	5	t	2026-09-20 15:00:00+00
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: catalog
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: catalog
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: catalog
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add content type	1	add_contenttype
2	Can change content type	1	change_contenttype
3	Can delete content type	1	delete_contenttype
4	Can view content type	1	view_contenttype
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: catalog
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: catalog
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: catalog
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: carrera; Type: TABLE DATA; Schema: public; Owner: catalog
--

COPY public.carrera (id, codigo, nombre, escuela, activa, creada_en) FROM stdin;
20000000-0000-4000-8000-000000000001	ING-INFO	Ingeniería en Informática	Informática y Telecomunicaciones	t	2026-09-20 15:00:00+00
20000000-0000-4000-8000-000000000002	ANA-PROG	Analista Programador Computacional	Informática y Telecomunicaciones	t	2026-09-20 15:00:00+00
20000000-0000-4000-8000-000000000003	ING-ADM	Ingeniería en Administración	Administración y Negocios	t	2026-09-20 15:00:00+00
20000000-0000-4000-8000-000000000004	DIS-GRAF	Diseño Gráfico	Comunicación	f	2026-09-20 15:00:00+00
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: catalog
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	contenttypes	contenttype
2	auth	permission
3	auth	group
4	auth	user
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: catalog
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-09-20 23:38:27.835809+00
2	contenttypes	0002_remove_content_type_name	2026-09-20 23:38:27.846949+00
3	auth	0001_initial	2026-09-20 23:38:28.025296+00
4	auth	0002_alter_permission_name_max_length	2026-09-20 23:38:28.045535+00
5	auth	0003_alter_user_email_max_length	2026-09-20 23:38:28.051166+00
6	auth	0004_alter_user_username_opts	2026-09-20 23:38:28.075608+00
7	auth	0005_alter_user_last_login_null	2026-09-20 23:38:28.091243+00
8	auth	0006_require_contenttypes_0002	2026-09-20 23:38:28.097436+00
9	auth	0007_alter_validators_add_error_messages	2026-09-20 23:38:28.109972+00
10	auth	0008_alter_user_username_max_length	2026-09-20 23:38:28.169495+00
11	auth	0009_alter_user_last_name_max_length	2026-09-20 23:38:28.215343+00
12	auth	0010_alter_group_name_max_length	2026-09-20 23:38:28.23267+00
13	auth	0011_update_proxy_permissions	2026-09-20 23:38:28.246767+00
14	auth	0012_alter_user_first_name_max_length	2026-09-20 23:38:28.276211+00
15	catalogo	0001_extensiones	2026-10-04 18:53:18.623451+00
16	catalogo	0002_modelo_inicial	2026-10-04 18:53:18.73254+00
\.


--
-- Data for Name: importacion_catalogo; Type: TABLE DATA; Schema: public; Owner: catalog
--

COPY public.importacion_catalogo (id, archivo, tipo, filas_leidas, filas_creadas, filas_omitidas, ejecutada_por, ejecutada_en) FROM stdin;
1	ejemplo_sedes.csv	SEDES	11	11	0	\N	2026-09-20 14:55:00+00
2	ejemplo_malla_ing_informatica_2024.csv	MALLA	15	14	1	\N	2026-09-20 15:00:00+00
\.


--
-- Data for Name: importacion_error; Type: TABLE DATA; Schema: public; Owner: catalog
--

COPY public.importacion_error (id, fila, mensaje, importacion_id) FROM stdin;
1	16	Semestre 13 fuera del rango de 1 a 12 (asignatura SEG3101): se omite la fila	2
\.


--
-- Data for Name: malla; Type: TABLE DATA; Schema: public; Owner: catalog
--

COPY public.malla (id, version, vigente_desde, vigente_hasta, creada_en, carrera_id) FROM stdin;
1	2024	2024-03-01	\N	2026-09-20 15:00:00+00	20000000-0000-4000-8000-000000000001
2	2020	2020-03-01	2024-02-29	2026-09-20 15:00:00+00	20000000-0000-4000-8000-000000000001
3	2024	2024-03-01	\N	2026-09-20 15:00:00+00	20000000-0000-4000-8000-000000000002
4	2023	2023-03-01	\N	2026-09-20 15:00:00+00	20000000-0000-4000-8000-000000000003
\.


--
-- Data for Name: malla_asignatura; Type: TABLE DATA; Schema: public; Owner: catalog
--

COPY public.malla_asignatura (id, semestre, asignatura_id, malla_id) FROM stdin;
1	1	40000000-0000-4000-8000-000000000001	1
2	1	40000000-0000-4000-8000-000000000005	1
3	1	40000000-0000-4000-8000-000000000006	1
4	1	40000000-0000-4000-8000-000000000003	1
5	2	40000000-0000-4000-8000-000000000007	1
6	2	40000000-0000-4000-8000-000000000002	1
7	2	40000000-0000-4000-8000-000000000010	1
8	2	40000000-0000-4000-8000-000000000004	1
9	3	40000000-0000-4000-8000-000000000008	1
10	3	40000000-0000-4000-8000-000000000009	1
11	3	40000000-0000-4000-8000-000000000014	1
12	4	40000000-0000-4000-8000-000000000011	1
13	4	40000000-0000-4000-8000-000000000012	1
14	4	40000000-0000-4000-8000-000000000013	1
15	1	40000000-0000-4000-8000-000000000001	2
16	1	40000000-0000-4000-8000-000000000005	2
17	2	40000000-0000-4000-8000-000000000006	2
18	2	40000000-0000-4000-8000-000000000007	2
19	1	40000000-0000-4000-8000-000000000001	3
20	1	40000000-0000-4000-8000-000000000005	3
21	1	40000000-0000-4000-8000-000000000006	3
22	2	40000000-0000-4000-8000-000000000007	3
23	2	40000000-0000-4000-8000-000000000008	3
24	2	40000000-0000-4000-8000-000000000002	3
25	3	40000000-0000-4000-8000-000000000009	3
26	3	40000000-0000-4000-8000-000000000012	3
27	4	40000000-0000-4000-8000-000000000011	3
28	4	40000000-0000-4000-8000-000000000003	3
29	1	40000000-0000-4000-8000-000000000015	4
30	1	40000000-0000-4000-8000-000000000001	4
31	1	40000000-0000-4000-8000-000000000002	4
32	2	40000000-0000-4000-8000-000000000016	4
33	2	40000000-0000-4000-8000-000000000004	4
34	2	40000000-0000-4000-8000-000000000003	4
35	3	40000000-0000-4000-8000-000000000017	4
36	3	40000000-0000-4000-8000-000000000018	4
37	4	40000000-0000-4000-8000-000000000019	4
38	4	40000000-0000-4000-8000-000000000020	4
\.


--
-- Data for Name: prerrequisito; Type: TABLE DATA; Schema: public; Owner: catalog
--

COPY public.prerrequisito (id, malla_asignatura_id, requiere_id) FROM stdin;
1	5	2
2	10	3
3	12	5
4	22	20
5	36	30
\.


--
-- Data for Name: sede; Type: TABLE DATA; Schema: public; Owner: catalog
--

COPY public.sede (id, codigo, nombre, region, activa) FROM stdin;
30000000-0000-4000-8000-000000000001	ALAMEDA	Alameda	Metropolitana	t
30000000-0000-4000-8000-000000000002	ANTONIO-VARAS	Antonio Varas	Metropolitana	t
30000000-0000-4000-8000-000000000003	MAIPU	Maipú	Metropolitana	t
30000000-0000-4000-8000-000000000004	PLAZA-OESTE	Plaza Oeste	Metropolitana	t
30000000-0000-4000-8000-000000000005	PLAZA-NORTE	Plaza Norte	Metropolitana	t
30000000-0000-4000-8000-000000000006	SAN-BERNARDO	San Bernardo	Metropolitana	t
30000000-0000-4000-8000-000000000007	PUENTE-ALTO	Puente Alto	Metropolitana	t
30000000-0000-4000-8000-000000000008	VINA-DEL-MAR	Viña del Mar	Valparaíso	t
30000000-0000-4000-8000-000000000009	VALPARAISO	Valparaíso	Valparaíso	t
30000000-0000-4000-8000-000000000010	CONCEPCION	Concepción	Biobío	t
30000000-0000-4000-8000-000000000011	SAN-JOAQUIN	San Joaquín	Metropolitana	t
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: catalog
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: catalog
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: catalog
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 16, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: catalog
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: catalog
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, false);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: catalog
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: catalog
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 4, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: catalog
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 16, true);


--
-- Name: importacion_catalogo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: catalog
--

SELECT pg_catalog.setval('public.importacion_catalogo_id_seq', 2, true);


--
-- Name: importacion_error_id_seq; Type: SEQUENCE SET; Schema: public; Owner: catalog
--

SELECT pg_catalog.setval('public.importacion_error_id_seq', 1, true);


--
-- Name: malla_asignatura_id_seq; Type: SEQUENCE SET; Schema: public; Owner: catalog
--

SELECT pg_catalog.setval('public.malla_asignatura_id_seq', 38, true);


--
-- Name: malla_id_seq; Type: SEQUENCE SET; Schema: public; Owner: catalog
--

SELECT pg_catalog.setval('public.malla_id_seq', 4, true);


--
-- Name: prerrequisito_id_seq; Type: SEQUENCE SET; Schema: public; Owner: catalog
--

SELECT pg_catalog.setval('public.prerrequisito_id_seq', 5, true);


--
-- Name: asignatura asignatura_pkey; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.asignatura
    ADD CONSTRAINT asignatura_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: carrera carrera_pkey; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.carrera
    ADD CONSTRAINT carrera_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: importacion_catalogo importacion_catalogo_pkey; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.importacion_catalogo
    ADD CONSTRAINT importacion_catalogo_pkey PRIMARY KEY (id);


--
-- Name: importacion_error importacion_error_pkey; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.importacion_error
    ADD CONSTRAINT importacion_error_pkey PRIMARY KEY (id);


--
-- Name: malla_asignatura malla_asignatura_pkey; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.malla_asignatura
    ADD CONSTRAINT malla_asignatura_pkey PRIMARY KEY (id);


--
-- Name: malla malla_pkey; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.malla
    ADD CONSTRAINT malla_pkey PRIMARY KEY (id);


--
-- Name: prerrequisito prerrequisito_pkey; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.prerrequisito
    ADD CONSTRAINT prerrequisito_pkey PRIMARY KEY (id);


--
-- Name: sede sede_pkey; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.sede
    ADD CONSTRAINT sede_pkey PRIMARY KEY (id);


--
-- Name: asignatura ux_asignatura_sigla; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.asignatura
    ADD CONSTRAINT ux_asignatura_sigla UNIQUE (sigla);


--
-- Name: carrera ux_carrera_codigo; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.carrera
    ADD CONSTRAINT ux_carrera_codigo UNIQUE (codigo);


--
-- Name: malla_asignatura ux_malla_asignatura; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.malla_asignatura
    ADD CONSTRAINT ux_malla_asignatura UNIQUE (malla_id, asignatura_id);


--
-- Name: malla ux_malla_carrera_version; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.malla
    ADD CONSTRAINT ux_malla_carrera_version UNIQUE (carrera_id, version);


--
-- Name: prerrequisito ux_prerrequisito; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.prerrequisito
    ADD CONSTRAINT ux_prerrequisito UNIQUE (malla_asignatura_id, requiere_id);


--
-- Name: sede ux_sede_codigo; Type: CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.sede
    ADD CONSTRAINT ux_sede_codigo UNIQUE (codigo);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: catalog
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: catalog
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: catalog
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: catalog
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: catalog
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: catalog
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: catalog
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: catalog
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: catalog
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: ix_asignatura_busqueda; Type: INDEX; Schema: public; Owner: catalog
--

CREATE INDEX ix_asignatura_busqueda ON public.asignatura USING gin (upper((sigla)::text) public.gin_trgm_ops, upper((nombre)::text) public.gin_trgm_ops);


--
-- Name: ix_carrera_activa; Type: INDEX; Schema: public; Owner: catalog
--

CREATE INDEX ix_carrera_activa ON public.carrera USING btree (activa, nombre);


--
-- Name: ix_importacion_error; Type: INDEX; Schema: public; Owner: catalog
--

CREATE INDEX ix_importacion_error ON public.importacion_error USING btree (importacion_id, fila);


--
-- Name: ix_importacion_fecha; Type: INDEX; Schema: public; Owner: catalog
--

CREATE INDEX ix_importacion_fecha ON public.importacion_catalogo USING btree (ejecutada_en DESC);


--
-- Name: ix_malla_asig_semestre; Type: INDEX; Schema: public; Owner: catalog
--

CREATE INDEX ix_malla_asig_semestre ON public.malla_asignatura USING btree (malla_id, semestre) INCLUDE (asignatura_id);


--
-- Name: ix_malla_carrera; Type: INDEX; Schema: public; Owner: catalog
--

CREATE INDEX ix_malla_carrera ON public.malla USING btree (carrera_id);


--
-- Name: ix_prerrequisito_origen; Type: INDEX; Schema: public; Owner: catalog
--

CREATE INDEX ix_prerrequisito_origen ON public.prerrequisito USING btree (malla_asignatura_id);


--
-- Name: ix_sede_activa; Type: INDEX; Schema: public; Owner: catalog
--

CREATE INDEX ix_sede_activa ON public.sede USING btree (activa, nombre);


--
-- Name: malla_asignatura_asignatura_id_50f6e017; Type: INDEX; Schema: public; Owner: catalog
--

CREATE INDEX malla_asignatura_asignatura_id_50f6e017 ON public.malla_asignatura USING btree (asignatura_id);


--
-- Name: prerrequisito_requiere_id_5be59242; Type: INDEX; Schema: public; Owner: catalog
--

CREATE INDEX prerrequisito_requiere_id_5be59242 ON public.prerrequisito USING btree (requiere_id);


--
-- Name: ux_malla_vigente; Type: INDEX; Schema: public; Owner: catalog
--

CREATE UNIQUE INDEX ux_malla_vigente ON public.malla USING btree (carrera_id) WHERE (vigente_hasta IS NULL);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: importacion_error importacion_error_importacion_id_9a5428c8_fk_importaci; Type: FK CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.importacion_error
    ADD CONSTRAINT importacion_error_importacion_id_9a5428c8_fk_importaci FOREIGN KEY (importacion_id) REFERENCES public.importacion_catalogo(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: malla_asignatura malla_asignatura_asignatura_id_50f6e017_fk_asignatura_id; Type: FK CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.malla_asignatura
    ADD CONSTRAINT malla_asignatura_asignatura_id_50f6e017_fk_asignatura_id FOREIGN KEY (asignatura_id) REFERENCES public.asignatura(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: malla_asignatura malla_asignatura_malla_id_7d07ac14_fk_malla_id; Type: FK CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.malla_asignatura
    ADD CONSTRAINT malla_asignatura_malla_id_7d07ac14_fk_malla_id FOREIGN KEY (malla_id) REFERENCES public.malla(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: malla malla_carrera_id_3332fcf2_fk_carrera_id; Type: FK CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.malla
    ADD CONSTRAINT malla_carrera_id_3332fcf2_fk_carrera_id FOREIGN KEY (carrera_id) REFERENCES public.carrera(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: prerrequisito prerrequisito_malla_asignatura_id_bee6ca87_fk_malla_asi; Type: FK CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.prerrequisito
    ADD CONSTRAINT prerrequisito_malla_asignatura_id_bee6ca87_fk_malla_asi FOREIGN KEY (malla_asignatura_id) REFERENCES public.malla_asignatura(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: prerrequisito prerrequisito_requiere_id_5be59242_fk_malla_asignatura_id; Type: FK CONSTRAINT; Schema: public; Owner: catalog
--

ALTER TABLE ONLY public.prerrequisito
    ADD CONSTRAINT prerrequisito_requiere_id_5be59242_fk_malla_asignatura_id FOREIGN KEY (requiere_id) REFERENCES public.malla_asignatura(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 5A5FC9jSeUYnA8KfyhlWRd2v46jTHhnv2qHYLrTHqh5nwwiMYu7w9rn2mOpUO7U

